// Generated by CoffeeScript 2.7.0
module.exports = function(settings = {}) {
  if (!settings.url) {
    throw Error('Invalid Settings: missing the `url` field');
  }
  if (!settings.author) {
    throw Error('Invalid Settings: missing the `author` field');
  }
  if (!settings.authorUrl) {
    throw Error('Invalid Settings: missing the `authorUrl` field');
  }
  return function(ast, vfile) {
    if (typeof settings.authorUrl === 'function') {
      settings.authorUrl = settings.authorUrl.call(null, ast, vfile);
    }
    if (typeof settings.authorUrl !== 'string') {
      throw Error(`Invalid authorUrl: expect a string, got ${settings.authorUrl}`);
    }
    // Add source information
    ast.children.push({
      type: 'paragraph',
      children: [
        {
          type: 'text',
          value: (function() {
            switch (vfile.data.lang) {
              case 'en':
                return 'This article was originally published by ';
              case 'fr':
                return 'Cet article fut publié à l\'origine par ';
            }
          })()
        },
        {
          type: 'link',
          url: settings.url,
          children: [
            {
              type: 'text',
              value: (function() {
                switch (vfile.data.lang) {
                  case 'en':
                    return 'Adaltas';
                  case 'fr':
                    return 'Adaltas';
                }
              })()
            }
          ]
        },
        {
          type: 'text',
          value: (function() {
            switch (vfile.data.lang) {
              case 'en':
                return ' and was written by ';
              case 'fr':
                return ' et fut rédigé par ';
            }
          })()
        },
        {
          type: 'link',
          url: settings.authorUrl,
          children: [
            {
              type: 'text',
              value: settings.author
            }
          ]
        },
        {
          type: 'text',
          value: '.'
        }
      ]
    });
    return null;
  };
};
