// Generated by CoffeeScript 2.5.1
var toText;

toText = require('hast-util-to-text');

/*
Normalize absolute link
*/
module.exports = function() {
  return function(ast, vfile) {
    var child, index, ref;
    if ((ref = vfile.frontmatter) != null ? ref.noTitleToFrontmatter : void 0) {
      return;
    }
    if (!ast.children.length) {
      return;
    }
    index = 0;
    if (ast.children[0].type === 'yaml') {
      index++;
    }
    child = ast.children[index];
    if (child.type === 'heading' && child.depth === 1) {
      if (vfile.frontmatter == null) {
        vfile.frontmatter = {};
      }
      if (!vfile.frontmatter.title) {
        vfile.frontmatter.title = toText(child);
      }
      ast.children.splice(index, 1);
    }
    return null;
  };
};
