// Generated by CoffeeScript 2.4.1
var path, visit;

path = require('path');

visit = require('unist-util-visit');

/*
Normalize absolute link
*/
module.exports = function(settings) {
  return function(tree, file) {
    // normalize_links = (node) ->
    //   if node.type is 'link' and /^\//.test node.url
    //     node.url = path.join 'http://www.adaltas.com/', node.url
    //   if node.children
    //     node.children.map (child) -> normalize_links child
    //   node
    // normalize_links ast
    return visit(tree, 'link', function(node) {
      if (settings.baseURL && /^\//.test(node.url)) {
        return node.url = path.join(settings.baseURL, node.url);
      }
    });
  };
};
