// Generated by CoffeeScript 2.5.1
var yaml;

yaml = require('js-yaml');

/*
Parse frontmatter and insert the "frontmatter" field in the vfile object.
*/
module.exports = function() {
  return function(ast, vfile) {
    var child, i, len, ref;
    ref = ast.children;
    // Extract frontmatter
    for (i = 0, len = ref.length; i < len; i++) {
      child = ref[i];
      if (child.type !== 'yaml') {
        continue;
      }
      vfile.frontmatter = yaml.safeLoad(child.value);
    }
    return null;
  };
};
