// Generated by CoffeeScript 2.5.1
var md_ast_to_string, visit;

visit = require('unist-util-visit');

md_ast_to_string = require('../utils/md_ast_to_string');

module.exports = function() {
  return function(tree, file) {
    return visit(tree, 'table', function(node) {
      var value;
      value = md_ast_to_string(node);
      node.type = 'code';
      node.lang = null;
      node.meta = null;
      node.value = value.trim();
      node.children = null;
      return null;
    });
  };
};
