// Generated by CoffeeScript 2.7.0
import readline from 'readline';

export default function(question) {
  return new Promise(function(resolve) {
    var rl;
    rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });
    return rl.question(`${question}: `, function(answer) {
      rl.close();
      return resolve(answer);
    });
  });
};
