// Generated by CoffeeScript 2.4.1
var stringify, unified;

unified = require('unified');

stringify = require('remark-stringify');

module.exports = function(ast, settings) {
  return unified().use(stringify).data('settings', settings || {}).stringify(ast);
};
