// Generated by CoffeeScript 2.5.1
var gfm, stringify, unified;

unified = require('unified');

stringify = require('remark-stringify');

gfm = require('remark-gfm');

module.exports = function(ast, settings) {
  return unified().use(stringify).use(gfm).data('settings', settings || {}).stringify(ast);
};
