// Generated by CoffeeScript 2.7.0
import {
  read
} from 'to-vfile';

import {
  unified
} from 'unified';

import doc from 'rehype-document';

import gfm from 'remark-gfm';

import markdownParse from 'remark-parse';

import remark2rehype from 'remark-rehype';

import frontmatter from 'remark-frontmatter';

import format from 'rehype-format';

import html from 'rehype-stringify';

export default async function(plugins, source) {
  var plugin, settings;
  return (await unified().use(markdownParse).use(gfm).use(frontmatter, ['yaml']).use((function() {
    var i, len, results;
    results = [];
    for (i = 0, len = plugins.length; i < len; i++) {
      ({plugin, settings} = plugins[i]);
      results.push([plugin, settings]);
    }
    return results;
  })()).use(remark2rehype).use(doc).use(format).use(html).process((await read(source))));
};
