// Generated by CoffeeScript 2.4.1
var doc, format, frontmatter, html, parse, remark2rehype, unified, vfile;

vfile = require('to-vfile');

unified = require('unified');

doc = require('rehype-document');

parse = require('remark-parse');

remark2rehype = require('remark-rehype');

frontmatter = require('remark-frontmatter');

format = require('rehype-format');

html = require('rehype-stringify');

module.exports = function(plugins, source) {
  return new Promise(function(resolve, reject) {
    var i, len, plugin, settings, u;
    u = unified();
    u.use(parse);
    u.use(frontmatter, ['yaml']);
    for (i = 0, len = plugins.length; i < len; i++) {
      ({plugin, settings} = plugins[i]);
      u.use(plugin, settings);
    }
    u.use(remark2rehype);
    u.use(doc);
    u.use(format);
    u.use(html);
    return u.process(vfile.readSync(source), function(err, file) {
      if (err) {
        return reject(err);
      }
      return resolve(file);
    });
  });
};
