// Generated by CoffeeScript 2.6.1
var doc, format, frontmatter, gfm, html, markdownParse, remark2rehype, unified, vfile;

vfile = require('to-vfile');

unified = require('unified');

doc = require('rehype-document');

gfm = require('remark-gfm');

markdownParse = require('remark-parse');

remark2rehype = require('remark-rehype');

frontmatter = require('remark-frontmatter');

format = require('rehype-format');

html = require('rehype-stringify');

module.exports = async function(plugins, source) {
  var plugin, settings;
  return (await unified().use(markdownParse).use(gfm).use(frontmatter, ['yaml']).use((function() {
    var i, len, results;
    results = [];
    for (i = 0, len = plugins.length; i < len; i++) {
      ({plugin, settings} = plugins[i]);
      results.push([plugin, settings]);
    }
    return results;
  })()).use(remark2rehype).use(doc).use(format).use(html).process((await vfile.read(source))));
};
